# Copyright 2026 Tim Korelov (https://github.com/lifestreamy)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Submit a Kobweb Project"
description: "Submit your project to be featured on the official Kobweb Showcase website!"
title: "Showcase Submission: <Your Site Name>"
labels: ["showcase-submission"]
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to the Kobweb Showcase!
        Fill out the form below to submit your project. A maintainer will review it shortly.
        *Please ensure your site is live and there is a single clear image of your app attached.*

  - type: input
    id: project-name
    attributes:
      label: "Project Name"
      description: "What is the name of your website or application?"
      placeholder: "e.g., My Awesome Kobweb App"
    validations:
      required: true

  - type: input
    id: live-url
    attributes:
      label: "Live URL"
      description: "Where is your project hosted?"
      placeholder: "e.g., my-app.example.com or https://my-app.example.com"
    validations:
      required: true

  - type: textarea
    id: image-url
    attributes:
      label: "Project Screenshot"
      description: "Drag and drop or paste (Ctrl + V) a single screenshot of your app here. GitHub will automatically upload it and generate a Markdown image link. **Please leave the generated markdown link exactly as is.**"
      placeholder: "Drag and drop your image here..."
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: "Project Description"
      description: "What does your site do? Give us a short pitch."
      placeholder: "This site is a portfolio showing off my..."
    validations:
      required: true

  - type: dropdown
    id: site-type
    attributes:
      label: "Site Type"
      description: "What is your website architecture?"
      options:
        - "Static Site (SSG)"
        - "Fullstack (Kobweb-native)"
        - "Fullstack (other backend)"
    validations:
      required: true

  - type: dropdown
    id: core-features
    attributes:
      label: "Core Features"
      description: "Select all the keywords that apply to your project."
      multiple: true
      options:
        - "Personal Portfolio"
        - "Animations"
        - "Commercial"
        - "Open Source"
        - "Complex UI"
    validations:
      required: false

  - type: input
    id: other-keywords
    attributes:
      label: "Other Keywords"
      description: "Any other features? (Semicolon separated)"
      placeholder: "e.g., JS/TS Integration; WebGL; Spring Boot; Web Components; SEO-optimized"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: "Submission Agreement"
      options:
        - label: "I confirm that this project is built using Kobweb and is safe for public viewing."
          required: true
